# Generated by Django 5.1.4 on 2024-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("level", models.IntegerField(blank=True, null=True)),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("未发", "未发"), ("已发", "已发")],
                        default="未发",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "salary_salary",
            },
        ),
        migrations.CreateModel(
            name="SalaryStandard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("standard_no", models.CharField(max_length=50)),
                ("standard_name", models.CharField(max_length=100)),
                ("creator", models.CharField(max_length=50)),
                ("creation_date", models.DateField()),
                ("registrar", models.CharField(max_length=50)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "standard_status",
                    models.CharField(
                        choices=[("有效", "有效"), ("无效", "无效")], max_length=10
                    ),
                ),
                (
                    "late_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "absence_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "full_attendance_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "salary_standard",
            },
        ),
    ]
