# Generated by Django 5.1.4 on 2024-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="manager",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
