# Generated by Django 5.1.4 on 2024-12-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="ability",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="experience",
        ),
    ]
