# Generated by Django 5.1.4 on 2024-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_remove_employee_ability_remove_employee_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="sex",
            field=models.CharField(choices=[("男", "男"), ("女", "女")], max_length=1),
        ),
    ]
