# Generated by Django 5.1.4 on 2024-12-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="sex",
            field=models.CharField(max_length=100),
        ),
    ]
