# Generated by Django 5.1.4 on 2024-12-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
