# Generated by Django 5.1.4 on 2024-12-21 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_department_employee_position'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='group.group'),
        ),
    ]
