# Generated by Django 5.1.4 on 2024-12-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_rename_group_employee_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="details",
            field=models.TextField(null=True),
        ),
    ]
