# Generated by Django 5.1.4 on 2024-12-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_group_employee_group'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.CharField(choices=[('技术部', '技术部'), ('市场部', '市场部'), ('人事部', '人事部'), ('财务部', '财务部'), ('行政部', '行政部'), ('研发部', '研发部'), ('销售部', '销售部'), ('客服部', '客服部'), ('运营部', '运营部'), ('采购部', '采购部'), ('售后部', '售后部'), ('公关部', '公关部'), ('战略部', '战略部'), ('人力资源部', '人力资源部'), ('法务部', '法务部')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
