# Generated by Django 5.1.4 on 2024-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_group_members_alter_group_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
