# Generated by Django 5.1.4 on 2024-12-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_alter_group_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
