# Generated by Django 5.1.4 on 2024-12-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_is_sign_in_attendance_is_sign_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="sign_in",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="sign_out",
            field=models.DateTimeField(null=True),
        ),
    ]
