# Generated by Django 5.1.4 on 2024-12-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_sign_in_alter_attendance_sign_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="data_id",
        ),
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
