# Generated by Django 5.1.4 on 2024-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_remove_attendance_data_id_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.TextField(null=True),
        ),
    ]
