# Generated by Django 5.1.4 on 2025-05-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendance_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_absent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_early",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
